### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nizar-tal** [KalleHallden/pwManager#10]
After choosing the 1 choice and arriving to this:
![image](https://user-images.githubusercontent.com/61629970/99424422-ef370a80-2901-11eb-94dd-e5930dcedf4b.png)
I don't know what I have to put in...
I supposed to be an url of the website but then whatever I enter I get this error:
![image](https://user-images.githubusercontent.com/61629970/99424590-27d6e400-2902-11eb-8f42-856e091dc02e.png)

I don't know why such a thing happens: is it because it is not meant to work on other machine? Or while filling it I made some mistakes?
Please @KalleHallden can you provide further explanations?

**Comment by uv-vudu** [comment]
@YoungMind44 This means that the program could not make changes to your database and could not find any accounts.

**Comment by nizar-tal** [comment]
But all the informations are all legit, yet I have the same error.I guess I enter something wrong in the last prompt.

**Comment by uv-vudu** [comment]
Check in your database while the program is running, see if it worked.

**Comment by nizar-tal** [comment]
Alright, I just noticed that I did not set up my database, and luckily you made a PR for that, what an idiot I am :/ thank you for you time!
