### ISSUE TITLE
i am so tired of this!!

### ISSUE THREAD

**Issue by Nikhil-Sudhan** [KalleHallden/pwManager#18]
Traceback (most recent call last):
  File "password_manager.py", line 2, in <module>
    from secrets import get_secret_key
ImportError: cannot import name 'get_secret_key' from 'secrets' (/usr/lib/python3.8/secrets.py)

This is a error I got and I use python3.7 .What are the other I need to do

**Comment by deepanshutiwari27** [comment]
> Traceback (most recent call last):
> File "password_manager.py", line 2, in
> from secrets import get_secret_key
> ImportError: cannot import name 'get_secret_key' from 'secrets' (/usr/lib/python3.8/secrets.py)
> 
> This is a error I got and I use python3.7 .What are the other I need to do

you don't have secrets module installed on your device. to install this module open your terminal and type following command:-
pip install secrets
